version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Pre-build phase...
  build:
    commands:
      - echo Build started...
      - npm run build
  post_build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - '**/*'
  discard-paths: no
